const sourceMetadataPatterns = [
  /^source:\s.*$/i,
  /^source title:\s.*$/i,
  /^source url:\s.*$/i,
  /^summary:\s.*$/i,
  /^trust:\s.*$/i,
  /^title:\s.*$/i,
  /^description:\s.*$/i,
  /^url source:\s.*$/i,
  /^markdown content:\s*$/i
];

const junkLinePatterns = [
  /^page\s+\d+(\s+of\s+\d+)?$/i,
  /^p\.\s*\d+$/i,
  /^\d+\s*\/\s*\d+$/,
  /^figure\s+\d+[a-z]?(?::|\s|$)/i,
  /^fig\.\s*\d+[a-z]?(?::|\s|$)/i,
  /^image\s+\d+(?::|\s|$)/i,
  /^illustration(?::|\s|$)/i,
  /^alt text(?::|\s|$)/i,
  /^caption(?::|\s|$)/i,
  /^header(?::|\s|$)/i,
  /^footer(?::|\s|$)/i,
  /^table of contents$/i,
  /^copyright\b/i,
  /^all rights reserved\b/i,
  /^downloaded from\b/i,
  /^retrieved from\b/i,
  /^printed from\b/i,
  /^generated by\b/i,
  /^ocr(?:\s+confidence)?(?::|\s|$)/i,
  /^scan(?:ned)? by\b/i,
  /^image placeholder\b/i,
  /^replacement text\b/i,
  /^photo credit\b/i,
  /^isbn(?:-1[03])?(?::|\s|$)/i,
  /^doi(?::|\s|$)/i
];

function normalizeWhitespace(text: string) {
  return text
    .replace(/\u0000/g, " ")
    .replace(/\r\n/g, "\n")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function looksLikeArtifact(line: string) {
  const trimmed = line.trim();
  if (!trimmed) return true;
  if (sourceMetadataPatterns.some((pattern) => pattern.test(trimmed))) return true;
  if (junkLinePatterns.some((pattern) => pattern.test(trimmed))) return true;
  if (/https?:\/\/\S+/i.test(trimmed) && trimmed.length < 140) return true;
  if (/^(?:www\.)\S+$/i.test(trimmed)) return true;
  if (/^\[[^\]]{0,80}\]$/.test(trimmed)) return true;
  if (/^\((?:image|figure|photo|diagram|table|header|footer|caption)[^)]+\)$/i.test(trimmed)) return true;
  if (/^(?:image|figure|photo|diagram|table|header|footer|caption)\s*[:|-]/i.test(trimmed)) return true;
  if (/^(?:chapter|section|unit)\s+\d+$/i.test(trimmed)) return true;
  if (/^[\d.\-_/| ]+$/.test(trimmed)) return true;
  if (trimmed.length < 3) return true;

  const letters = (trimmed.match(/[a-z]/gi) ?? []).length;
  const digits = (trimmed.match(/\d/g) ?? []).length;
  const symbols = (trimmed.match(/[^a-z0-9\s]/gi) ?? []).length;
  if (!letters && digits > 0) return true;
  if (symbols > letters * 1.5 && trimmed.length < 80) return true;

  return false;
}

function removeRepeatedFurniture(lines: string[]) {
  const frequency = new Map<string, number>();

  lines.forEach((line) => {
    const normalized = line.trim().toLowerCase();
    if (!normalized || normalized.length < 4 || normalized.length > 120) return;
    frequency.set(normalized, (frequency.get(normalized) ?? 0) + 1);
  });

  return lines.filter((line) => {
    const normalized = line.trim().toLowerCase();
    const count = frequency.get(normalized) ?? 0;
    if (count < 3) return true;
    if (line.length > 90) return true;
    if (/[.!?]/.test(line)) return true;
    return false;
  });
}

function fixBrokenLines(lines: string[]) {
  const merged: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      if (merged[merged.length - 1] !== "") {
        merged.push("");
      }
      continue;
    }

    const previous = merged[merged.length - 1];
    if (
      previous &&
      previous !== "" &&
      !/[.!?:]$/.test(previous) &&
      !/^[A-Z][a-z]+:/.test(line) &&
      !/^(?:-|\*|\d+[.)])\s/.test(line) &&
      line.length < 140
    ) {
      merged[merged.length - 1] = `${previous} ${line}`.replace(/\s+/g, " ").trim();
      continue;
    }

    merged.push(line);
  }

  return merged;
}

export function cleanStudySourceText(text: string) {
  const normalized = normalizeWhitespace(
    text
      .replace(/(\w)-\n(\w)/g, "$1$2")
      .replace(/\t/g, " ")
      .replace(/\b[\w-]+\.(pdf|docx|txt|png|jpe?g|xlsx?|csv|md)\b/gi, " ")
  );

  if (!normalized) return "";

  const strippedLines = normalized
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => !looksLikeArtifact(line));

  const withoutRepeatedFurniture = removeRepeatedFurniture(strippedLines);
  const repaired = fixBrokenLines(withoutRepeatedFurniture);

  return normalizeWhitespace(
    repaired
      .join("\n")
      .replace(/\n(?=[a-z(])/g, " ")
      .replace(/\s+/g, " ")
      .replace(/\n /g, "\n")
  );
}

export function sanitizeInlineStudyText(text: string) {
  return normalizeWhitespace(
    cleanStudySourceText(text)
      .replace(/\|/g, " / ")
      .replace(/\[[^\]]*\]/g, " ")
      .replace(/\((?:https?:\/\/|www\.)[^)]*\)/gi, " ")
      .replace(/https?:\/\/\S+/gi, " ")
  );
}
