export type SeoPageKey =
  | "studyTools"
  | "flashcards"
  | "quiz"
  | "revisionPlanner"
  | "aiStudyAssistant"
  | "onlineLearning"
  | "examPreparation"
  | "homeworkHelp"
  | "studyTechniques"
  | "academicSuccess";

export type SeoPageContent = {
  metadata: {
    title: string;
    description: string;
    keywords: string;
  };
  eyebrow: string;
  title: string;
  description: string;
  primaryCta: string;
  highlights: string[];
  steps: Array<{ title: string; copy: string }>;
  outcomes: Array<{ title: string; copy: string }>;
  faqs: Array<{ question: string; answer: string }>;
  related: Array<{ href: string; label: string }>;
};

const baseSteps = [
  {
    title: "Add your study sources",
    copy: "Upload notes, PDFs, images, spreadsheets, or import a readable web source into a studio."
  },
  {
    title: "Keep the AI grounded",
    copy: "ScholarMind uses source-enabled files as the evidence base, so generated tools stay tied to your material."
  },
  {
    title: "Revise from several angles",
    copy: "Move between AI tutor chat, summaries, AI Notes, quizzes, flashcards, exam practice, and revision schedules."
  }
];

const relatedCore = [
  { href: "/ai-study-assistant", label: "AI study assistant" },
  { href: "/quiz-maker", label: "Quiz maker" },
  { href: "/flashcard-generator", label: "Flashcards" },
  { href: "/revision-planner", label: "Revision planner" }
];

export const seoPages: Record<SeoPageKey, SeoPageContent> = {
  studyTools: {
    metadata: {
      title: "Best AI Study Tools for Students | ScholarMind",
      description: "Use ScholarMind to turn notes, PDFs, images, and web sources into AI Notes, summaries, quizzes, flashcards, mock exams, and revision schedules.",
      keywords: "AI study tools, online study tools, student revision tools, AI notes, quiz generator, flashcard generator"
    },
    eyebrow: "AI study tools",
    title: "Study tools that start from your real notes.",
    description: "ScholarMind is built for students who want source-grounded revision tools instead of generic AI answers. Add your material once, then generate the study outputs you need from the same studio.",
    primaryCta: "Open study tools",
    highlights: [
      "Generate summaries, AI Notes, quizzes, flashcards, and mock exams from enabled sources.",
      "Open generated outputs as Studio tabs so the tutor can help with the exact result on screen.",
      "Use source controls to exclude files that should not count toward chat, tools, or schedules."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "AI Notes", copy: "Longer textbook-style notes with examples, formulas, callouts, and practice questions." },
      { title: "Quiz practice", copy: "Multiple-choice questions with answers, explanations, and a results table." },
      { title: "Flashcards", copy: "Large swipeable recall cards generated from real source concepts." },
      { title: "Exam practice", copy: "Practice-question mode or longer mock papers with mark allocations." }
    ],
    faqs: [
      { question: "Are tools generated by AI?", answer: "Yes. Study tools now require a live configured AI provider and do not silently fall back to placeholder local output." },
      { question: "Can I use sources from the web?", answer: "Yes. Scholar mode prioritises trusted academic and learning sources, then imported web text is cleaned before becoming a study source." }
    ],
    related: relatedCore
  },
  flashcards: {
    metadata: {
      title: "AI Flashcard Generator from Notes | ScholarMind",
      description: "Create source-grounded flashcards from uploaded notes, PDFs, images, and readable web sources with ScholarMind.",
      keywords: "AI flashcard generator, flashcards from notes, active recall cards, study cards"
    },
    eyebrow: "Flashcards",
    title: "Turn notes into active-recall flashcards.",
    description: "Generate concise flashcards from the exact material in your studio, then swipe through them one by one and track practice inside the same workspace.",
    primaryCta: "Generate flashcards",
    highlights: [
      "Cards are created from enabled source files, not random topic guesses.",
      "Large card mode supports next/back movement and keyboard-friendly review.",
      "Tutor chat can help explain a card without losing the current study context."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Front/back cards", copy: "Short prompts with clear memory answers." },
      { title: "Source-grounded recall", copy: "Terms, formulas, facts, and definitions pulled from the uploaded material." },
      { title: "Review rhythm", copy: "Move quickly through cards and reopen saved decks later." },
      { title: "Tutor support", copy: "Ask the tutor to explain a card step by step." }
    ],
    faqs: [
      { question: "Does it make generic flashcards?", answer: "The prompt is designed to avoid generic cards and require source-specific recall cues." },
      { question: "Can I ask chat to make flashcards?", answer: "Yes. Asking the tutor for flashcards triggers the tool generation path and opens the result as a Studio tab." }
    ],
    related: relatedCore
  },
  quiz: {
    metadata: {
      title: "AI Quiz Maker from Study Notes | ScholarMind",
      description: "Generate multiple-choice quizzes from uploaded study sources, answer them online, and review a results table.",
      keywords: "AI quiz maker, quiz generator from notes, multiple choice quiz, revision quiz"
    },
    eyebrow: "Quiz maker",
    title: "Create quizzes from the material you actually need to learn.",
    description: "ScholarMind builds multiple-choice questions from enabled sources, then lets you answer inside the workspace and review your results.",
    primaryCta: "Create a quiz",
    highlights: [
      "Questions are source-specific and avoid silly distractors like generic labels.",
      "Answers and explanations are shown after you attempt a question.",
      "Quiz performance feeds the study metrics used by the tutor."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Interactive answering", copy: "Choose options, reveal explanations, and move through each question." },
      { title: "Results table", copy: "See selected answer, correct answer, and explanation rows." },
      { title: "Personalised help", copy: "The tutor can guide without revealing answers too early." },
      { title: "Export", copy: "Export quiz data as JSON or printable output where available." }
    ],
    faqs: [
      { question: "Will the tutor give away answers?", answer: "For quiz and exam help, it is instructed to guide with hints and method before revealing final answers." },
      { question: "Can quizzes match my exam context?", answer: "The prompt includes the student's onboarding profile, such as country, curriculum, exam board, and tier when available." }
    ],
    related: relatedCore
  },
  revisionPlanner: {
    metadata: {
      title: "AI Revision Planner and Study Schedule | ScholarMind",
      description: "Build revision schedules from exam details and uploaded class notes, with daily study sessions linked back to your sources.",
      keywords: "revision planner, AI study schedule, exam timetable, revision schedule"
    },
    eyebrow: "Revision planner",
    title: "Plan what to study next without losing your sources.",
    description: "Create a separate revision schedule workspace for an exam, then open each planned day as a focused study session connected to your source stack.",
    primaryCta: "Plan revision",
    highlights: [
      "Schedules are separate from the live Studio so planning does not interrupt studying.",
      "Each day can be marked complete, skipped, edited, or opened as a study session.",
      "Plans use uploaded notes and goals instead of a generic calendar."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Exam-based plan", copy: "Tell ScholarMind the exam and date, then generate a plan." },
      { title: "Daily tabs", copy: "Each day has a focus, task, and check." },
      { title: "Editable progress", copy: "Mark completion and adjust days as needed." },
      { title: "Source-linked sessions", copy: "Open a day back into Studio with the right sources loaded." }
    ],
    faqs: [
      { question: "Is the planner free?", answer: "The revision schedule mode is available in the app preview and follows the same account-backed source model." },
      { question: "Can I change the plan?", answer: "Yes. Days can be edited and progress is stored with the account." }
    ],
    related: relatedCore
  },
  aiStudyAssistant: {
    metadata: {
      title: "AI Study Assistant for Source-Grounded Tutoring | ScholarMind",
      description: "Ask a personalised AI tutor questions about uploaded notes, PDFs, images, and source-enabled web imports.",
      keywords: "AI study assistant, AI tutor, homework help AI, source grounded AI"
    },
    eyebrow: "AI tutor",
    title: "A study assistant that can see your enabled sources.",
    description: "Ask normal questions, casual questions, or step-by-step study questions. The tutor uses your source-enabled material, study profile, and current workspace context.",
    primaryCta: "Ask the tutor",
    highlights: [
      "Casual chat works, but study answers stay grounded to uploaded material.",
      "The tutor can suggest or trigger study tools such as quizzes, flashcards, AI Notes, and exams.",
      "Screen-aware context helps it explain the current workspace tab or generated output."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Direct answer first", copy: "Responses start with the answer, then show the reasoning." },
      { title: "Step-by-step help", copy: "Useful for maths, science, exam questions, and confusing notes." },
      { title: "Tool ecosystem", copy: "Ask the tutor to generate a quiz, flashcards, notes, or a mock exam." },
      { title: "Personalisation", copy: "Onboarding context shapes level, curriculum, and explanation style." }
    ],
    faqs: [
      { question: "Can I just say hi?", answer: "Yes. Casual conversation is handled separately from source-grounded study questions." },
      { question: "Does it know my sources?", answer: "It receives cleaned text from enabled files and imported sources in the current studio." }
    ],
    related: relatedCore
  },
  onlineLearning: {
    metadata: {
      title: "Online Learning Workspace for Students | ScholarMind",
      description: "Use an online learning workspace with uploaded sources, AI tutor chat, study tools, revision schedules, and secure account-backed progress.",
      keywords: "online learning workspace, student learning platform, AI learning tools"
    },
    eyebrow: "Online learning",
    title: "One workspace for notes, tutor chat, and revision outputs.",
    description: "ScholarMind combines uploaded-source grounding, AI-generated study tools, and revision planning so students can move from information overload into active recall.",
    primaryCta: "Open workspace",
    highlights: [
      "Studios keep sources, outputs, chat history, and progress grouped by topic.",
      "Source search can pull in trusted references when students do not have enough notes.",
      "Mind Security Engine adds route protection, upload checks, and security headers."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Studios", copy: "Separate notebooks for classes, subjects, or exams." },
      { title: "AI tutor", copy: "Personal help grounded to the current workspace." },
      { title: "Study outputs", copy: "Summaries, AI Notes, quizzes, flashcards, and exams." },
      { title: "Account sync", copy: "Progress and settings follow the signed-in user." }
    ],
    faqs: [
      { question: "Is this a course platform?", answer: "No. It is a study workspace for making your own notes and sources easier to revise from." },
      { question: "Does it work on mobile?", answer: "The public pages and workspace are designed to collapse for smaller screens, with heavier canvas-style features best on desktop." }
    ],
    related: relatedCore
  },
  examPreparation: {
    metadata: {
      title: "AI Exam Preparation Tools | ScholarMind",
      description: "Prepare for exams with source-grounded AI Notes, quizzes, flashcards, mock papers, and revision schedules.",
      keywords: "AI exam preparation, mock exam generator, GCSE revision AI, A level revision AI"
    },
    eyebrow: "Exam preparation",
    title: "Practise for exams from your actual class material.",
    description: "Generate quick practice questions or longer mock papers from uploaded sources, then use the tutor to work through methods without instantly revealing answers.",
    primaryCta: "Prepare for exams",
    highlights: [
      "Exam Generator includes a full mock mode and a shorter practice-question mode.",
      "Mock papers include instructions, marks, sections, and a compact mark scheme.",
      "Weekly exam-generation limits protect shared AI usage during preview."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Mock paper", copy: "Longer exam-style output for serious practice." },
      { title: "Practice questions", copy: "Shorter question sets when a full paper is too much." },
      { title: "Mark scheme", copy: "Review expected points and answers after attempting." },
      { title: "Tutor guidance", copy: "Get hints and methods before final answers." }
    ],
    faqs: [
      { question: "Does it copy real exam papers?", answer: "No. It generates new practice from your sources and profile rather than copying copyrighted papers." },
      { question: "Why are full exams limited?", answer: "They are heavier AI runs, so weekly limits protect the shared API budget." }
    ],
    related: relatedCore
  },
  homeworkHelp: {
    metadata: {
      title: "AI Homework Help with Step-by-Step Guidance | ScholarMind",
      description: "Use ScholarMind for source-grounded homework explanations, hints, tables, formulas, and step-by-step study guidance.",
      keywords: "AI homework help, step by step homework, study tutor, maths help AI"
    },
    eyebrow: "Homework help",
    title: "Get help understanding homework, not just answers.",
    description: "ScholarMind is designed to guide students through source-backed explanations, methods, formulas, and practice without turning every question into an answer dump.",
    primaryCta: "Get study help",
    highlights: [
      "For quiz and exam-style questions, the tutor gives hints and method before final answers.",
      "Maths-friendly formatting supports formulas, tables, and worked reasoning.",
      "Uploaded class notes keep explanations aligned with what the student is actually studying."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Clear explanations", copy: "Break confusing topics into smaller steps." },
      { title: "Method support", copy: "Work through calculations, definitions, and essay planning." },
      { title: "Mini checks", copy: "Ask for one-question practice inside chat." },
      { title: "Study tools", copy: "Turn homework topics into revision outputs." }
    ],
    faqs: [
      { question: "Will it just solve my homework?", answer: "The tutor is prompted to teach the method and guide attempts, especially for practice and exam questions." },
      { question: "Can it help with maths?", answer: "Yes. It can use formula-style notation, tables, and step-by-step reasoning where needed." }
    ],
    related: relatedCore
  },
  studyTechniques: {
    metadata: {
      title: "Effective Study Techniques with AI Support | ScholarMind",
      description: "Use active recall, spaced practice, AI flashcards, quizzes, and revision schedules with ScholarMind.",
      keywords: "study techniques, active recall, spaced repetition, AI revision, study methods"
    },
    eyebrow: "Study techniques",
    title: "Use proven study methods inside one AI workspace.",
    description: "ScholarMind turns active recall, self-testing, summaries, flashcards, and revision scheduling into practical workflows based on your own notes.",
    primaryCta: "Try study techniques",
    highlights: [
      "Flashcards and quizzes support active recall from source material.",
      "Revision schedules help distribute study across days instead of cramming.",
      "AI Notes give a deeper reading pass before practice begins."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Active recall", copy: "Generate questions and cards to test memory." },
      { title: "Spaced review", copy: "Plan revision days and reopen daily sessions." },
      { title: "Elaboration", copy: "Ask the tutor to explain why concepts matter." },
      { title: "Feedback loop", copy: "Quiz results and flips feed performance context." }
    ],
    faqs: [
      { question: "What technique should I start with?", answer: "Upload sources, create a quick summary, then move into flashcards or a quiz for active recall." },
      { question: "Can it make a plan?", answer: "Yes. The revision planner creates a separate schedule from exam details and uploaded notes." }
    ],
    related: relatedCore
  },
  academicSuccess: {
    metadata: {
      title: "Academic Success with AI Revision Tools | ScholarMind",
      description: "Improve study consistency with source-grounded AI tutoring, revision tools, exam practice, and account-backed progress.",
      keywords: "academic success, improve grades, AI revision tools, study habits"
    },
    eyebrow: "Academic success",
    title: "Build a study loop you can actually keep using.",
    description: "ScholarMind helps students move from passive rereading into source-grounded explanations, active recall, practice, and planned revision.",
    primaryCta: "Build a study loop",
    highlights: [
      "Studios keep each subject or exam organised.",
      "Tutor chat, study tools, and saved outputs stay tied to the same source stack.",
      "Settings and progress are account-backed so students can continue across devices."
    ],
    steps: baseSteps,
    outcomes: [
      { title: "Better organisation", copy: "Separate studios for subjects, units, and exams." },
      { title: "Less passive rereading", copy: "Turn notes into practice tasks and explanations." },
      { title: "More targeted revision", copy: "Use quizzes, flashcards, and schedules to decide what comes next." },
      { title: "Safer workflow", copy: "Mind Security Engine adds protection around accounts, uploads, and abuse." }
    ],
    faqs: [
      { question: "Does it guarantee grades?", answer: "No tool can guarantee grades, but it can make revision more structured and active." },
      { question: "What makes it different?", answer: "The workspace links sources, tutor chat, generated tools, revision plans, and account-backed progress together." }
    ],
    related: relatedCore
  }
};
